-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."news" add column "company_only_flag" boolean
--  not null default 'true';
