org: anhtutran
app: company885-lambda
service: company885-lambda

frameworkVersion: '2'
custom:
  apiKeys:
    - company-885-app-api-key-dev
  prune:
    automatic: true
    number: 1
  splitStacks:
    perFunction: false
    perType: false
    perGroupFunction: true
    nestedStackCount: 5
  vpc:
    # Functions for the CI stage are deployed in the default VPC.
    # Functions for the production stage are deployed in the "beat-production" VPC.
    # production:
    #   securityGroupIds:
    #     - "sg-0d526bd0fb1666f5a" # beat-production-lambda
    #   subnetIds:
    #     - "subnet-0df94e658e18954d6" # beat-production-1a-with-nat
    #     - "subnet-02dd48df2883ea199" # beat-production-1c-with-nat
provider:
  name: aws
  runtime: nodejs14.x

  environment:
    JWT_ENCRYPTION_KEY: ${file(config.json):JWT_ENCRYPTION_KEY}
    S3_ACCESS_KEY: ${file(config.json):S3_ACCESS_KEY}
    S3_SECRET_ACCESS_KEY: ${file(config.json):S3_SECRET_ACCESS_KEY}
    HASURA_ADMIN_SECRET: ${file(config.json):HASURA_ADMIN_SECRET}
    HASURA_ENDPOINT: ${file(config.json):HASURA_ENDPOINT}
    S3_REGION: "ap-northeast-1"
  region: us-east-1
  apiKeys:
    - company-885-app-api-key-dev

functions:
  # hello:
  #   handler: handler.hello
  use_if_need_job:
    handler: functions/use_if_need_job.handler
    # iamRoleStatements: # [Optional] these statements will be applied to this function only (in addition to statements that are applied to all functions)
    #   - Effect: "Allow"
    #     Action:
    #       - "cloudwatch:GetMetricStatistics"
    #       - "cloudwatch:DescribeAlarms"
    #       - "cloudwatch:PutMetricData"
    #     Resource: "*"
    events:
      - http:
          path: use_if_need_job
          method: post
          # private: true
